import Link from "next/link";
import { ArrowLeft, Gavel, Zap } from "lucide-react";

export default function TermsPage() {
  const lastUpdated = "April 3, 2026";

  return (
    <div className="min-h-screen bg-background text-foreground py-20 px-6 relative overflow-hidden">
      {/* Background Decorative Elements */}
      <div className="absolute top-[-10%] right-[-10%] w-[40%] h-[40%] bg-primary/10 blur-[120px] rounded-full" />
      <div className="absolute bottom-[-10%] left-[-10%] w-[40%] h-[40%] bg-accent/10 blur-[120px] rounded-full" />

      <div className="max-w-4xl mx-auto relative z-10">
        <div className="bg-card/50 backdrop-blur-xl border border-white/5 shadow-saas rounded-3xl p-8 md:p-16">
          <Link href="/" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-500 hover:text-primary dark:hover:text-accent mb-12 transition-colors group">
            <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> Back to Home
          </Link>
          
          <header className="border-b border-white/5 pb-10 mb-10">
            <div className="flex items-center gap-4 mb-4">
              <div className="h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary flex shadow-lg shadow-primary/5">
                <Gavel size={24} />
              </div>
              <div>
                <h1 className="text-3xl font-black tracking-tightest text-foreground uppercase">Terms of Service</h1>
                <p className="text-[10px] text-slate-600 uppercase tracking-widest font-black mt-1">Last Revised: {lastUpdated}</p>
              </div>
            </div>
          </header>

          <div className="space-y-12 text-slate-500 dark:text-slate-400 text-sm md:text-base leading-relaxed font-medium">
            <section>
              <h2 className="text-xl font-black text-foreground mb-4 tracking-tight flex items-center gap-2">
                <span className="text-accent italic">1.</span> Use License
              </h2>
              <p>Permission is granted to temporarily access the materials (information or software) on STRIVE's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.</p>
            </section>

            <section className="bg-red-500/5 p-8 rounded-3xl border border-red-500/10">
              <h2 className="text-xl font-black text-red-400 mb-4 tracking-tight flex items-center gap-2">
                <span className="italic">2.</span> AI SEO Disclaimer
              </h2>
              <p className="text-red-400/80 font-bold mb-4 uppercase text-xs tracking-widest">The service provides recommendations generated by artificial intelligence. You expressly understand and agree that:</p>
              <ul className="space-y-3 text-sm">
                <li className="flex items-start gap-2">
                  <div className="h-1.5 w-1.5 rounded-full bg-red-400/50 mt-1.5 shrink-0" />
                  <span>We do not guarantee any specific ranking improvement on Google or other search engines.</span>
                </li>
                <li className="flex items-start gap-2">
                  <div className="h-1.5 w-1.5 rounded-full bg-red-400/50 mt-1.5 shrink-0" />
                  <span>We are not responsible for the accuracy of code snippets provided by the AI.</span>
                </li>
                <li className="flex items-start gap-2">
                  <div className="h-1.5 w-1.5 rounded-full bg-red-400/50 mt-1.5 shrink-0" />
                  <span>Traffic fluctuations are the result of third-party algorithms beyond our control.</span>
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-black text-foreground mb-4 tracking-tight flex items-center gap-2">
                <span className="text-accent italic">3.</span> User Conduct & Security
              </h2>
              <p>You may not use the Service for any illegal purpose or to violate any laws in your jurisdiction. Any attempt to bypass security filters, including URL validation protocols, will result in the immediate termination of your access without refund.</p>
            </section>

            <section>
              <h2 className="text-xl font-black text-foreground mb-4 tracking-tight flex items-center gap-2">
                <span className="text-accent italic">4.</span> Limitation of Liability
              </h2>
              <p>In no event shall STRIVE or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the Service.</p>
            </section>
          </div>

          <footer className="mt-16 pt-10 border-t border-white/5 text-center">
             <div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary mb-4">
                <Zap size={20} />
             </div>
             <p className="text-[10px] font-black uppercase tracking-widest text-slate-600">Building a more transparent web with STRIVE.</p>
          </footer>
        </div>
      </div>
    </div>
  );
}