import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "./ThemeProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const googleId=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
  //define the core layout exactly once
  //added main so the footer is forced to the bottom
  const AppContent=(
    <ThemeProvider>
      <Navbar/>
      <main className="flex-grow flex flex-col">
        {children}
      </main>
      <Footer/>
    </ThemeProvider>
  );
  return (
    //suppressHydrationWarning is CRUCIAL here, it stops Next.js from throwing an error
    //when next-themes injects the dark mode class on page load.
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {googleId? (
         <GoogleOAuthProvider clientId={googleId}>
            {AppContent}
          </GoogleOAuthProvider>):(

            AppContent
          
          )}
      </body>
    </html>
  );
}
