import Link from "next/link";
import { ArrowLeft, Gavel } from "lucide-react";

export default function TermsPage() {
  const lastUpdated = "April 3, 2026";

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 py-16 px-6 font-sans">
      <div className="max-w-4xl mx-auto bg-white shadow-sm border border-slate-200 rounded-2xl p-8 md:p-12">
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-[#15418c] mb-8 transition-colors">
          <ArrowLeft size={16} /> Back to Home
        </Link>
        
        <header className="border-b border-slate-100 pb-8 mb-8">
          <div className="flex items-center gap-3 mb-2">
            <Gavel className="text-[#15418c]" size={28} />
            <h1 className="text-3xl font-bold tracking-tight text-slate-900">Terms of Service</h1>
          </div>
          <p className="text-xs text-slate-500 uppercase tracking-widest font-semibold">Last Revised: {lastUpdated}</p>
        </header>

        <div className="space-y-8 text-slate-700 text-sm md:text-base leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3 underline decoration-[#15418c]/20 underline-offset-4">1. Use License</h2>
            <p>Permission is granted to temporarily access the materials (information or software) on STRIVE's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.</p>
          </section>

          <section className="bg-red-50 p-6 rounded-xl border border-red-100">
            <h2 className="text-lg font-bold text-red-900 mb-2">2. AI SEO Disclaimer & Non-Guarantee</h2>
            <p className="text-red-800 font-medium mb-2">THE SERVICE PROVIDES RECOMMENDATIONS GENERATED BY ARTIFICIAL INTELLIGENCE. YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</p>
            <ul className="list-disc pl-5 space-y-1 text-red-800 text-sm">
              <li>WE DO NOT GUARANTEE ANY SPECIFIC RANKING IMPROVEMENT ON GOOGLE OR OTHER SEARCH ENGINES.</li>
              <li>WE ARE NOT RESPONSIBLE FOR THE ACCURACY OF CODE SNIPPETS PROVIDED BY THE AI.</li>
              <li>TRAFFIC FLUCTUATIONS ARE THE RESULT OF THIRD-PARTY ALGORITHMS BEYOND OUR CONTROL.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3 underline decoration-[#15418c]/20 underline-offset-4">3. User Conduct & Security</h2>
            <p>You may not use the Service for any illegal purpose or to violate any laws in your jurisdiction. Any attempt to bypass security filters, including URL validation protocols, will result in the immediate termination of your access without refund.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 mb-3 underline decoration-[#15418c]/20 underline-offset-4">4. Limitation of Liability</h2>
            <p>In no event shall STRIVE or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the Service.</p>
          </section>
        </div>
      </div>
    </div>
  );
}